http:
  # port: 8282
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

dataFilePath:
  sms: /home/antares/MEGA/Go/monitoring-system/sms.data
  email: /home/antares/MEGA/Go/monitoring-system/email.data
  voiceCall: /home/antares/MEGA/Go/monitoring-system/voice.data
  billing: /home/antares/MEGA/Go/monitoring-system/billing.data

dataUrl:
  mms: http://localhost:8383/mms
  incident: http://localhost:8383/accendent
  support: http://localhost:8383/support

cache:
  expiration: 30s
  cleanupInterval: 10s
